### ISSUE TITLE
Birthday bugged on checked in page

### ISSUE THREAD

**Issue by Kevinjchang98** [Kevinjchang98/St-Francis#96]
Discussed on Sept 27 meeting

**Comment by lmeng25** [comment]
Description: customer birthday offsets by one day on profile page.
![image](https://github.com/Kevinjchang98/St-Francis/assets/98987608/f75242bb-2220-4c14-8fe3-cf31e707c7d4)

**Comment by lmeng25** [comment]
solved in #97
